---
- name: Test-Playbook zur Überprüfung der Web-Interface-Integration
  hosts: localhost
  gather_facts: no

  vars:
    subnet: "{{ subnet | default('unset') }}"
    nat: "{{ nat | default('unset') }}"
    hostname: "{{ hostname | default('unset') }}"
    server_type: "{{ server_type | default('unset') }}"
    location: "{{ location | default('unset') }}"
    is_enabled: "{{ is_enabled | default('false') }}"
  tasks:
    - name: Ausgabe der übergebenen Variablen
      debug:
        msg:
          - "Test-Playbook ausgeführt!"
          - "Subnet: {{ subnet }}"
          - "NAT: {{ nat }}"
          - "Hostname: {{ hostname }}"
          - "Server-Typ: {{ server_type }}"
          - "Location: {{ location }}"
          - "Checkbox: {{ is_enabled }}"
